### ISSUE TITLE
Request to Add Product in Start Svelte Website

### ISSUE THREAD

**Issue by maheshwari-1153** [wobsoriano/coderstats#1]
Hello, 

I am Maheshwari Shukla from the [GeekyAnts](https://geekyants.com/) team. 

We are tech enthusiasts & love the open-source community.
 
We ourselves have built many open source products, which you can check [here](https://geekyants.com/products).

One of our recent open-source contributions is in Svelte. 

We have a website named [Start Svelte](http://startsvelte.com/) where we add open source UI's or apps so that it can help other developers. 

Let me know if you are interested to showcase your product on our open-source website. 

If yes, then I request you to add MIT Licence in your repo. 

Looking forward to hearing from you.

**Comment by wobsoriano** [comment]
Hi,

That's a great site! Would love to see the app there. MIT License added.

Thank you.

**Comment by maheshwari-1153** [comment]
Hey,

Thanks for getting back so quickly. It would be helpful if you can add more UI examples in the repo.

**Comment by wobsoriano** [comment]
Sorry I don't understand. You mean add more screenshots of the app in the readme?

**Comment by maheshwari-1153** [comment]
Yes, excatly.

**Comment by wobsoriano** [comment]
Will check, but there's a sample gif already
